export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'


//UI
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'
export const SET_ERRORS = 'SET_ERRORS'
export const NO_ERRORS = 'NO_ERRORS'

//USER POSTS
export const USER_POST_CHANGE = 'USER_POST_CHANGE'

//FOLLOWS
export const USER_FOLLOWS_CHANGE = 'USER_FOLLOWS_CHANGE'

//USER DATA
export const USER_DATA_STATE_CHANGE = 'USER_DATA_STATE_CHANGE'
export const USER_POST_STATE_CHANGE = 'USER_POST_STATE_CHANGE'

